console.log('load:GameConfig.js');

(function () {
    window.GameConfig = {
        WinScore:1000,
        Aircraft: {
            score: 0,
            lifeVlue: 20,
            speed: 4,
            width: 35,
            height: 35,
            bulletCoolDownTime: 300,
			bulletCount:4,
            bulletSpeed: -5.8,
            bulletWidth: 3,
            bulletHeight: 6,
        },
        DifficultyModel: [
            {
                name:'关卡1',
                MeetScores: 0,
                MoveSpeed:2,
                ProBase: 10000,
                CreatedEnemyPor:35,
                FirePro: 500,
                LeftMovePro: 10,
                RightMovePro: 10,
                UpMovePro: 100,
                DownMovePro: 8,
                LiftValue1Pro: 1,
                ScoresValue: 1,
            },
            {
                name: '关卡2',
                MeetScores: 20,
                MoveSpeed: 2,
                ProBase: 10000,
                CreatedEnemyPor: 35,
                FirePro: 400,
                LeftMovePro: 9,
                RightMovePro: 9,
                UpMovePro: 150,
                DownMovePro: 8,
                LiftValue1Pro: 1,
                liftValue2Pro: 8,
                ScoresValue: 1,
            }, {
                name: '关卡3',
                MeetScores: 40,
                MoveSpeed: 2,
                ProBase: 10000,
                CreatedEnemyPor: 30,
                FirePro: 300,
                LeftMovePro: 8,
                RightMovePro: 8,
                UpMovePro: 200,
                DownMovePro: 7,
                liftValue2Pro: 7,
                ScoresValue: 1,
            }, {
                name: '关卡4',
                MeetScores: 80,
                MoveSpeed: 2,
                ProBase: 10000,
                CreatedEnemyPor: 30,
                FirePro: 250,
                LeftMovePro: 8,
                RightMovePro: 8,
                UpMovePro: 200,
                DownMovePro: 6,
                liftValue2Pro: 6,
                ScoresValue: 2,
            }, {
                name: '关卡5',
                MeetScores: 160,
                MoveSpeed: 2,
                ProBase: 10000,
                CreatedEnemyPor: 30,
                FirePro: 200,
                LeftMovePro: 7,
                RightMovePro: 7,
                UpMovePro: 100,
                DownMovePro: 6,
                liftValue2Pro: 5,
                liftValue3Pro: 6,
                ScoresValue: 2,
            }, {
                name: '关卡6',
                MeetScores: 320,
                MoveSpeed: 2,
                ProBase: 10000,
                CreatedEnemyPor: 30,
                FirePro: 150,
                LeftMovePro: 7,
                RightMovePro: 7,
                UpMovePro: 200,
                DownMovePro: 5,
                liftValue2Pro: 4,
                liftValue3Pro: 5,
                ScoresValue: 3,
            }, {
                name: '关卡7',
                MeetScores: 640,
                MoveSpeed:3,
                ProBase: 10000,
                CreatedEnemyPor: 20,
                FirePro:120,
                LeftMovePro: 6,
                RightMovePro: 6,
                UpMovePro: 300,
                DownMovePro: 5,
                liftValue2Pro: 3,
                liftValue3Pro: 4,
                ScoresValue: 3,
            }, {
                name: '关卡8',
                MeetScores: 900,
                MoveSpeed: 4,
                ProBase: 10000,
                CreatedEnemyPor: 20,
                FirePro:100,
                LeftMovePro: 6,
                RightMovePro: 6,
                UpMovePro: 400,
                DownMovePro: 4,
                liftValue2Pro: 2,
                liftValue3Pro: 3,
                ScoresValue: 3,
            }
        ]
    };
}());

